export const Users = [
    {
        id:1,
        profilePicture: "assets/person/1.jpg",
        username: "Eggatha Christie",
    },
    {
        id:2,
        profilePicture: "assets/person/2.jpg",
        username: "Abrahen Lincoln",
    },
    {
        id:3,
        profilePicture: "assets/person/3.jpg",
        username: "Sal Monella",
    },
    {
        id:4,
        profilePicture: "assets/person/4.jpg",
        username: "Angelina Jopeep",
    },
    {
        id:5,
        profilePicture: "assets/person/5.jpg",
        username: "Babz",
    },
    {
        id:6,
        profilePicture: "assets/person/6.jpg",
        username: "Chick Jagger",
    },
    {
        id:7,
        profilePicture: "assets/person/7.jpg",
        username: "Cluck Norris",
    },
    {
        id:8,
        profilePicture: "assets/person/8.jpg",
        username: "Henifer Aniston",
    },
    {
        id:9,
        profilePicture: "assets/person/9.jpg",
        username: "Tootsie",
    },
    {
        id:10,
        profilePicture: "assets/person/10.jpg",
        username: "Yolko Ono",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "Imma head out with some friends! :D",
        photo: "assets/post/1.jpg",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        desc: "Made some breakfast",
        photo: "assets/post/2.jpg",
        date: "15 mins ago",
        userId: 2,
        like: 9,
        comment: 3,
    },
    {
        id: 3,
        desc: "Selfie :3",
        photo: "assets/post/3.jpg",
        date: "17 mins ago",
        userId: 3,
        like: 12,
        comment: 2,
    },
    {
        id: 4,
        photo: "assets/post/4.png",
        date: "26 mins ago",
        userId: 4,
        like: 24,
        comment: 5,
    },
    {
        id: 5,
        desc: "I painted this today.",
        photo: "assets/post/5.jpg",
        date: "38 mins ago",
        userId: 5,
        like: 38,
        comment: 3,
    },
    {
        id: 6,
        desc: "Hunky mf <3",
        photo: "assets/post/6.jpg",
        date: "45 mins ago",
        userId: 6,
        like: 420,
        comment: 69,
    },
    {
        id: 7,
        desc: "Me and my gf <3",
        photo: "assets/post/7.jpg",
        date: "1 hour ago",
        userId: 7,
        like: 78,
        comment: 12,
    },
    {
        id: 8,
        desc: "I love my kids.",
        photo: "assets/post/8.jpg",
        date: "1 hour ago",
        userId: 8,
        like: 15,
        comment: 7,
    },
    {
        id: 9,
        desc: "I got a new drip today!",
        photo: "assets/post/9.jpg",
        date: "1 hour ago",
        userId: 9,
        like: 98,
        comment: 17,
    },
    {
        id: 10,
        desc: "Anyone wanna play Minecraft with me?",
        photo: "assets/post/10.jpg",
        date: "2 hours ago",
        userId: 10,
        like: 1,
        comment: 1,
    },
];

//Continue 1:24:23